### ISSUE TITLE
Ignore ARB String returns null

### ISSUE THREAD

**Issue by amin79** [theLee3/flutter_auto_translator#11]
Hello.
I have this code:

```
"iban": "IBAN",
  "@iban": {
    "translator": {
      "ignore": true
    }
  },
```

But it sets` "iban": null `to all translated files. 

Is it a normal behaviour?

**Comment by theLee3** [comment]
No, this bug must have been introduced alongside recent changes. Thanks for bringing it to my attention. Working on a fix now.

**Comment by theLee3** [comment]
Fixed in 2.3.1, available now.

**Comment by amin79** [comment]
Thank's for your great package and support :)

**Comment by amin79** [comment]
Now instead of NULL, it's completely removed. It should be like this or it's another problem?

**Comment by theLee3** [comment]
This is the correct behavior. If you choose not to translate a value, it is not added to the translated ARB file. The app will fallback to the default ARB file. So in this case, IBAN will be used for each language.
