### ISSUE TITLE
Space after placeholder is removed

### ISSUE THREAD

**Issue by orkun1675** [theLee3/flutter_auto_translator#4]
Thank you for the awesome package! It has saved me a great amount of time.

English entry:

```
  "youFinished": "You finished {artwork}",
  "@youFinished": {
    "placeholders": {
      "artwork": {
        "type": "String",
        "example": "Mona Lisa"
      }
    }
  },
```

when translated to `Turkish (TR)` becomes:

```
    "youFinished": "{artwork}bitirdiniz",
```

while it should be: `{artwork} bitirdiniz` or ideally `{artwork}'yi bitirdiniz`

In Turkish the noun is moved to the beginning of the sentence. I'm guessing because in the original message there is no space after the placeholder the translated message has the space incorrectly removed?

**Comment by theLee3** [comment]
I'm glad you have found the package helpful @orkun1675.

Your theory is likely correct. I imagine the placeholder moving from the end of the sentence is an edge case that causes the missing space. I will implement a fix shortly. Hopefully, there is an approach that will reach the ideal translation, but some results are limited by cloud translate.

I will also have to check to see how punctuation affects this issue.

**Comment by theLee3** [comment]
Update 2.0.1 no longer removes the added whitespace. Please pull from GitHub for now.

```yaml
auto_translator:
    git:
      url: https://github.com/theLee3/flutter_auto_translator
```

I am leaving this open as I have devised a solution to make it more accurate in circumstances like this, i.e. to ensure `{artwork}'yi bitirdiniz` in this scenario.

**Comment by theLee3** [comment]
As of 2.1.0 translations use placeholder examples when available.

Please let me know how it works for you after pulling from GitHub. I will update on pub.dev if you have no issues.

**Comment by orkun1675** [comment]
I deleted the TR translation file and re-generated it. Works like a charm. Thanks @theLee3 !

**Comment by theLee3** [comment]
Awesome! Thanks for your help @orkun1675.

Update 2.1.0 is now available via [pub.dev](https://pub.dev/packages/auto_translator)
