### ISSUE TITLE
[Feature request] Retain file organizers during translation

### ISSUE THREAD

**Issue by orkun1675** [theLee3/flutter_auto_translator#5]
Hello,

As you know l10n files can get quite large and hard to maintain. As the number of strings increase it gets difficult to remember which page/widget tthey are used in.

There is an outstanding [issue in Flutter](https://github.com/flutter/flutter/issues/107157) that requests splitting up ARB files. In the meantime, we are using the syntax described [here](https://stackoverflow.com/questions/74984979/flutter-internationalization-how-to-break-down-arb-files-into-separate-files) to organize our ARB file.

Example:

```
  "@@locale": "en",
  "@_PAGE_LOGIN": {},
  "loginWithGameServices": "Login with {provider}",
  "@loginWithGameServices": {
    "placeholders": {
      "provider": {
        "type": "String",
        "example": "Game Center"
      }
    }
  },
  "@_PAGE_PLAY": {},
  "saveChanges": "Save",
  "progressNotSaved": "Progress not saved!",
```

The values with prefix `@_` are used as dividers since JSON doesn't support comments.

Would it be possible to retain these lines during the auto translation flow?

This would help human translators navigate the generated auto translation file and fix issues.

**Comment by theLee3** [comment]
Done. Also adds `@@locale` if used in the template.

I have to update the docs and finish writing some tests. I also want to improve the command line output before publishing. In the meantime, please pull version 2.2.0 from GitHub and provide any feedback you have.
